---
title: "DataAssignment_2"
author: "Md. Saifur Rahman"
date: "1/30/2021"
output: word_document
---
```{r setup working directory}
# Setup working directory for the assignment
setwd("C:/Users/mdsaifur.rahman.1/Desktop/Spring 2021/EFR 535/Code R")
```

```{r load packages}
# install and load "tidyverse" package to work with ggplot2
#install.packages("tidyverse")
library(tidyverse)
#load "tibble" package to see data in tibble format!
library(tibble)
```

```{r load, view, and attach Tophat data}
library(readxl)
Data <- read_excel("EFR 535 Assign 2 - Data Tophat - Jan 18 2018.xls", 
    na = "NA")
View(Data)
attach(Data)
```

```{r Examine Tophat data with tibble}
#Examine the Tophat data set with a tibble
Data
# same previous task but using as_tibble() function from "tibble" package
as_tibble(Data)
```
```{r mean and range functions}
# Average and range of Tophat participation percent column
mean(Tophat_participation_percent)
range(Tophat_participation_percent)
# Average and range of Final Grade percent
mean(Final_Grade_percent)
range(Final_Grade_percent)
```

```{r ggplot2 graphic template to create a scatterplot}
#  A Scatter plot comparing Tophat participation percent ( in x axis) and Final Grade percent (in y axis)
ggplot(data = Data) + geom_point( mapping = aes(x = Tophat_participation_percent, y = Final_Grade_percent))
```
```{r jitter the Data}
# There is a little difference in positioning of the dots in the scatter plot after adding "jitter" that is ignorable.This means the position of these values are mostly unique. There are a few values with the same or almost same position in this coordinate system with the given data. Most have different positioning values.  
ggplot(data = Data) + geom_point( mapping = aes(x = Tophat_participation_percent, y = Final_Grade_percent), position = "jitter")
```
```{r Create small multiples of the scatterplot based on Program of Study2 variable}
# facets
ggplot(data = Data) + geom_point( mapping = aes(x = Tophat_participation_percent, y = Final_Grade_percent)) + facet_wrap(~Program_of_Study2)
# This facet_warp() divide the single scatterplot and present the same data in a group of scatter plots based on number of groups find in the "Program_of_Study2" variable. In the Program_of_Study2 variable there are 3 groups (i) Medical Laboratory Science, (ii) Pre-Nursing, and (iii) Other. Most students are from the Pre-nursing group and their final grade percent increases according to the increase in the Tophat participation percent.  
```
```{r Examine Program of Study2 by including the variable as an aesthetic based on EACH of color, shape, size, and transparency.}
#  based on color
ggplot(data = Data) + geom_point( mapping = aes(x = Tophat_participation_percent, y = Final_Grade_percent, color = Program_of_Study2))
# based on shape
ggplot(data = Data) + geom_point( mapping = aes(x = Tophat_participation_percent, y = Final_Grade_percent, shape = Program_of_Study2))
# based on size
ggplot(data = Data) + geom_point( mapping = aes(x = Tophat_participation_percent, y = Final_Grade_percent, size = Program_of_Study2))
# based on transparency
ggplot(data = Data) + geom_point( mapping = aes(x = Tophat_participation_percent, y = Final_Grade_percent, alpha = Program_of_Study2))
# From this four aesthetics my preference is "color" (when work with one aesthetic). Color makes this scatterplot more presentable. This also help me to differentiate the type of color(which color means what) by providing a legend.
```
```{r Choose your favorites to make one plot with two aesthetics applied together}
# Sometimes multiple aesthetics make a graph more presentable. I am using the "color" and "shape" aesthetics here. Different color and different shape to plot the data, make this graph more understandable and presentable.  
ggplot(data = Data) + geom_point( mapping = aes(x = Tophat_participation_percent, y = Final_Grade_percent, color = Program_of_Study2, shape = Program_of_Study2))

```
```{r smooth line}
# Presentation of data in a graph by using a smooth line.
ggplot(data = Data) + geom_smooth( mapping = aes(x = Tophat_participation_percent, y = Final_Grade_percent))
# Make the same above code more efficient by using a global mapping of the x- and y-axis
ggplot(data = Data, mapping = aes(x = Tophat_participation_percent, y = Final_Grade_percent)) + geom_smooth()
```
```{r Select a new theme for this graph}
# I prefer to use classic theme because this is clean!
ggplot(data = Data, mapping = aes(x = Tophat_participation_percent, y = Final_Grade_percent)) + geom_smooth() + theme_classic()
```


